version: "2.1"
services:
    calibre-web:
        image: lscr.io/linuxserver/calibre-web:latest
        container_name: calibre-web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - DOCKER_MODS=ghcr.io/blitzmann/calibre-web-humble #optional
            - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
        volumes:
            - I:\My Drive:/books
            - H:\.calibre-web:/config
        ports:
            - 8083:8083
        restart: unless-stopped
